# Site settings
title:       Pea53
tagline:     Software and Such
description: I'm Tim Pease. I ride bikes and write software. I build fun things at <a href="https://github.com" target="_blank">GitHub</a>.
url:         http://pea53.com
baseurl:     "" # the subpath of your site, e.g. /blog

author:
  name:    Tim Pease
  github:  TwP
  twitter: pea53

# Build settings
permalink: /:year/:month/:title
markdown:  kramdown
paginate:  5
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
